version: '3'

networks:
  app-tier:
    driver: bridge

services:
  hw11:
    build: .
    nerworks:
    - app-tier
    ports:
    - "8010:8010"
    depends_on:
    - dbpsql
    volumes:
    - ".:/hw11/src/app/"
dbpsql:
  image: postgres:12
  ports:
    - "5432:5432"
  env_file:
    - .env
  environment:
    - POSTGRES_USER
    - POSTGRES_PASSWORD
    - POSTGRES_DB
  networks:
    - app-tier 
          